### PR TITLE
fix: remove dangling namespaces from system tests

### PR DESCRIPTION
**Pull request by zregvart**
Adds `-Dnamespace.destroy.enabled=true` which according to the
[Arquillian Cube documentation](http://arquillian.org/arquillian-cube/#_namespaces)
should delete the dangling namespace.

### CODE REVIEW

**Comment by zregvart** [comment]
That certainly is a way to delete the dangling namespaces but it seems that the Jenkins service account that we use doesn't have the necessary access rights:

```
DELETE at: https://kubernetes.default.svc/oapi/v1/projects/e2e-n75wm. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:syndesis-ci:builder" cannot delete projects in project "e2e-n75wm"
```

**Comment by zregvart** [comment]
@jimmidyson @iocanel @rhuss any idea on how can we give this privilege to Jenkins?

**Comment by iocanel** [comment]
AFAIR, project are created using the syndesis-ci:jenkins service account which has the self-provisioner role. The role should allow the service account to create projects and have full admin access to them. 

Not sure, why the service account in the logs is builder (though I do vaguely remember experimenting with that, so it may be ).

**Comment by iocanel** [comment]
In theory `-Dnamespace.destroy.enabled=true` shouldn't have to be explicitly specified as its the default behavior whenever a namespace is not specified (when its managed by arquillian).

In the case where the namespace is managed externally (e.g. its managed by https://github.com/syndesisio/kubernetes-pipeline-plugin/tree/arquillian/arquillian-steps) deleting the namespace should be the responsibility of whoever manages the namespace. 

Where  I am getting at is that  `-Dnamespace.destroy.enabled=true` should only be added when namespace is not externally specified and not in all cases.

**Comment by zregvart** [comment]
@iocanel does this make more sense?

**Review by iocanel — APPROVED** [review]
Yeah, that's more like it.

**Comment by iocanel** [comment]
retest this please

**Pull request merged**
